services:
  - type: web
    name: blockchain-voting-backend
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        value: your-secure-jwt-secret
      - key: MONGODB_URI
        value: mongodb://localhost:27017/voting_system