services:
  - type: web
    name: blockchain-voting-backend
    env: node
    buildCommand: |
      npm install -g truffle
      npm install
      truffle compile
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        value: your-secure-jwt-secret
      - key: MONGODB_URI
        value: mongodb+srv://mdanas8200:<db_password>@voting-system.3limyzu.mongodb.net/voting_system?retryWrites=true&w=majority